### ISSUE TITLE
Apply template changes

### ISSUE THREAD

**Issue by lenguyenthanh** [divvun/project-dadmin#48] opened 2020-04-02 12:39 UTC
I need more information for this task.

**Comment by snomos** [comment] 2020-04-02 12:53
So the workflow now (in svn) goes like this:

1. I need to update/change X in all languages
1. I edit X in the template, and commit it, together with a timestamp file
1. then I loop over all languages, and for each language Z, I do:
1. check a language-specific timestamp file to identify the time Y when it was last merged from the template
1. create a diff for the template, for the template changes since Y
1. apply the diff to Z, so that the change X is added to it
1. update the language specific timestamp file to record the new last-changed timestamp

The changes supported by this in svn are:

- file edits
- file additions

Sometimes I also need to move or delete files, those operations are not supported by the current setup, and I instead have to restort to a manual loop. But file edits and additions are by far the most common operations, so that has not been a major issue.

The present setup also differentiate between *safe* files and *unsafe* files, ie files that are considered unproblematic to merge (ie should not cause conflicts), and those that are prone to conflicts. Files prone to conflicts are those with linguistic content that people tend to edit - still there are times I need to add or change something also in such files. In case of conflicts I either resort to manual conflict resolution (not very scaleable) or just decide that if there is a conflict, then the new edit is not worth it, so I just revert my change in that language.

**Comment by snomos** [comment] 2020-04-02 13:08
This is a duplicate of #44 . I close it.

**Closed by snomos** 2020-04-02 13:08 UTC
Labels: question
